### ISSUE TITLE
Watchtower Icon is Blank

### ISSUE THREAD

**Issue by Starstrike** [homarr-labs/dashboard-icons#882]
### Contribution Guidelines

- [X] I have read and agree to the [Contribution Guidelines](https://github.com/homarr-labs/dashboard-icons/blob/main/CONTRIBUTING.md)

### Icon Name

watchtower

### Icon Details

The icon already exists in the repository but it's blank. This causes the icon to not show up on services such as gethomepage.

Link to the icon: https://github.com/homarr-labs/dashboard-icons/blob/main/png/watchtower.png

**Comment by ajnart** [comment]
Looking at the history of the file it seems like like 442e8f9d7784b23d07fb972f2572a851146615bc

Is the culprit, we need to check that commit to make sure other icons haven't been "optimized" out of existence as well

**Comment by Starstrike** [comment]
I noticed that the Commafeed icon looked a little different now too. Like it's grayed out. It should be orange.

Could be related to that optimization.

Thanks for taking a look!

**Comment by Druidblack** [comment]
To avoid creating a theme for each application.

Jellycat - the icon does not load
pfsense - the icon has changed color from blue to black.
esphome - the icon has changed color from blue to black

**Comment by walkxcode** [comment]
Fixed with https://github.com/homarr-labs/dashboard-icons/pull/890

**Comment by Starstrike** [comment]
> Fixed with #890

Just to clarify, can you show that it's fixed? When I pull up https://github.com/homarr-labs/dashboard-icons/blob/main/png/watchtower.png, the icon is still blank. Commafeed is still a dark gray color.

Is there some time that we need to wait for the icons to show back up?

**Comment by walkxcode** [comment]
It looks like the compression CI is causing issues with the SVGs. I’ll disable the CI until I can implement a fix. The icons should be working again in a few minutes.

**Comment by walkxcode** [comment]
Upon further investigation, I found that the newly provided SVGs from the projects are often not actual SVG files but images embedded within them. This is causing the compression CI to break. I’ve replaced them with true SVGs from other sources. If you notice anything else broken, please let us know.

**Comment by Starstrike** [comment]
Hmm...I'm not sure if this is something I need to bring up to @shamoon because the icons mentioned here are still not showing up. I've recreated the Homepage container, tried incognito, etc.

Despite what's been done here, I haven't seen any change to the icons in Homepage. I'm not sure if Homepage needs an update to make sure these are pulling correctly. He did update to use this repository. That's when I noticed the icons that weren't working/displaying properly.

**Comment by walkxcode** [comment]
It'll probably be caching. Try submitting the icons (jsDelivr) URL here https://www.jsdelivr.com/tools/purge.

**Comment by Starstrike** [comment]
Ah interesting. So the watchtower icon is here: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/watchtower.png

When I pull that up separately, it's definitely not the icon. Though, when I put that URL into the page you linked, it did say Success. Don't know how long that takes to happen though.

**Comment by walkxcode** [comment]
From experience Cloudflare and Fastly caching can take anywhere from a couple of minutes to 24 hours.

**Comment by walkxcode** [comment]
Commafeed seems to be also caching for now. Looks fine on git.

**Comment by Starstrike** [comment]
Yep ok. Just checked it again on Git and does look good. Alright! I'll check back in tomorrow or whenever I notice it's updated. Cache gonna make us wait lol.

**Comment by taylorabranson** [comment]
Found another... Dozzle

**Comment by walkxcode** [comment]
Dozzle got updated yesterday, should be caching now.

**Comment by Starstrike** [comment]
Watchtower and Commafeed are showing up properly now! They were yesterday, but I forgot to comment lol.
